POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlcmdpbyIsImlkIjoiNjNlNGRmZDI1ZThhZjYzYzVhNjEyOTc1IiwiaWF0IjoxNjc2MDIyMjk4fQ.anNjm6H7z73JjN_9_1CIuI0GJQx-YOKkZ1e2EYMAQ4A

{
  "title": "GitHub",
  "author": "sergio",
  "url": "https://www.github.com/yunsuklee",
  "userId": "63e4dfd25e8af63c5a612975"
}

### 

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlcmdpbyIsImlkIjoiNjNlNGRmZDI1ZThhZjYzYzVhNjEyOTc1IiwiaWF0IjoxNjc2MDIzMDY3fQ.pZKZtZ1Y4zK-xi0nj5oNi-ozOcIq-ZibEvZUboHLBOU

{
  "title": "freeCodeCamp",
  "author": "sergio",
  "likes": 500,
  "url": "https://www.freecodecamp.org",
  "userId": "63e4dfd25e8af63c5a612975"
}

###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzZTIzNzMxZDY1MTJjZWM0M2E5M2RkOCIsImlhdCI6MTY3NjAyODA1MX0.wTqxdpv2ie_PNMIa3qCtRgeyjGN13zNgrbeEk9TY96o

{
  "title": "FullStackOpen",
  "author": "root",
  "url": "https://www.fullstackopen.com",
  "userId": "63e23731d6512cec43a93dd8"
}
