POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "sergio",
  "password": "sergio"
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "root"
}

### Wrong username

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "notSergio",
  "password": "sergio"
}

### Wrong password

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "sergio",
  "password": "notSergio"
}